[package]
name = "tpt-simd"
description = "Umbrella crate re-exporting all tpt-simd crates"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = []
std = ["tpt-simd-core/std"]
nightly = ["tpt-simd-core/nightly"]
scalar-only = ["tpt-simd-core/scalar-only"]

[dependencies]
tpt-simd-core.workspace = true

[lints]
workspace = true
