[package]
name = "tpt-simd-dot"
description = "SIMD dot product variants"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = []
std = ["tpt-simd-core/std", "tpt-simd-horizontal/std"]
nightly = ["tpt-simd-core/nightly", "tpt-simd-horizontal/nightly"]
scalar-only = ["tpt-simd-core/scalar-only", "tpt-simd-horizontal/scalar-only"]

[dependencies]
tpt-simd-core.workspace = true
tpt-simd-horizontal = { path = "../tpt-simd-horizontal", version = "0.1.0" }

[dev-dependencies]
proptest.workspace = true
tpt-simd-testutil.workspace = true
criterion = { workspace = true, features = ["cargo_bench_support"] }

[lints]
workspace = true

[[bench]]
name = "dot"
harness = false
