[package]
name = "tpt-simd-aligned"
description = "SIMD-aligned memory types and helpers"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = ["alloc"]
alloc = []
std = ["alloc", "tpt-simd-core/std"]
nightly = ["tpt-simd-core/nightly"]
scalar-only = ["tpt-simd-core/scalar-only"]

[dependencies]
tpt-simd-core.workspace = true

[dev-dependencies]
proptest.workspace = true
tpt-simd-testutil.workspace = true

[lints]
workspace = true
